// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEdeSRFpTDSYufODtpzulKpm7UXb3oR2A',
    appId: '1:456868758603:web:9a07a66dc96916be64b9ce',
    messagingSenderId: '456868758603',
    projectId: 'hopewyse-69c83',
    authDomain: 'hopewyse-69c83.firebaseapp.com',
    databaseURL: 'https://hopewyse-69c83-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hopewyse-69c83.appspot.com',
    measurementId: 'G-QMCKT2P61H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvK0aFLvxDqYr2WsCXqgwGGYhGKvBwiLk',
    appId: '1:456868758603:android:768e9632f1b1461e64b9ce',
    messagingSenderId: '456868758603',
    projectId: 'hopewyse-69c83',
    databaseURL: 'https://hopewyse-69c83-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hopewyse-69c83.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqhpYjpkdKS0F-sTMJCMk9-gBQ_ePNIow',
    appId: '1:456868758603:ios:94d96fc979643c6964b9ce',
    messagingSenderId: '456868758603',
    projectId: 'hopewyse-69c83',
    databaseURL: 'https://hopewyse-69c83-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hopewyse-69c83.appspot.com',
    androidClientId: '456868758603-1amtspf7n9c2rlbvsjcbcli9ti3lan6b.apps.googleusercontent.com',
    iosClientId: '456868758603-ee9uv3hk734bictdrbs8217ud4a3qkvn.apps.googleusercontent.com',
    iosBundleId: 'com.example.hopewyse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqhpYjpkdKS0F-sTMJCMk9-gBQ_ePNIow',
    appId: '1:456868758603:ios:94d96fc979643c6964b9ce',
    messagingSenderId: '456868758603',
    projectId: 'hopewyse-69c83',
    databaseURL: 'https://hopewyse-69c83-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hopewyse-69c83.appspot.com',
    androidClientId: '456868758603-1amtspf7n9c2rlbvsjcbcli9ti3lan6b.apps.googleusercontent.com',
    iosClientId: '456868758603-ee9uv3hk734bictdrbs8217ud4a3qkvn.apps.googleusercontent.com',
    iosBundleId: 'com.example.hopewyse',
  );
}
